runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: macOS Ventura Version 13.5.2 (22G91)

manual_scaling:
  instances: 1
  
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
